<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;


class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // Africa
            ['name' => 'Algeria', 'continent' => 'Africa', 'code' => '+213'],
            ['name' => 'Angola', 'continent' => 'Africa', 'code' => '+244'],
            ['name' => 'Benin', 'continent' => 'Africa', 'code' => '+229'],
            ['name' => 'Botswana', 'continent' => 'Africa', 'code' => '+267'],
            ['name' => 'Burkina Faso', 'continent' => 'Africa', 'code' => '+226'],
            ['name' => 'Burundi', 'continent' => 'Africa', 'code' => '+257'],
            ['name' => 'Cabo Verde', 'continent' => 'Africa', 'code' => '+238'],
            ['name' => 'Cameroon', 'continent' => 'Africa', 'code' => '+237'],
            ['name' => 'Central African Republic', 'continent' => 'Africa', 'code' => '+236'],
            ['name' => 'Chad', 'continent' => 'Africa', 'code' => '+235'],
            ['name' => 'Comoros', 'continent' => 'Africa', 'code' => '+269'],
            ['name' => 'Congo', 'continent' => 'Africa', 'code' => '+242'],
            ['name' => 'Democratic Republic of the Congo', 'continent' => 'Africa', 'code' => '+243'],
            ['name' => 'Djibouti', 'continent' => 'Africa', 'code' => '+253'],
            ['name' => 'Egypt', 'continent' => 'Africa', 'code' => '+20'],
            ['name' => 'Equatorial Guinea', 'continent' => 'Africa', 'code' => '+240'],
            ['name' => 'Eritrea', 'continent' => 'Africa', 'code' => '+291'],
            ['name' => 'Eswatini', 'continent' => 'Africa', 'code' => '+268'],
            ['name' => 'Ethiopia', 'continent' => 'Africa', 'code' => '+251'],
            ['name' => 'Gabon', 'continent' => 'Africa', 'code' => '+241'],
            ['name' => 'Gambia', 'continent' => 'Africa', 'code' => '+220'],
            ['name' => 'Ghana', 'continent' => 'Africa', 'code' => '+233'],
            ['name' => 'Guinea', 'continent' => 'Africa', 'code' => '+224'],
            ['name' => 'Guinea-Bissau', 'continent' => 'Africa', 'code' => '+245'],
            ['name' => 'Ivory Coast', 'continent' => 'Africa', 'code' => '+225'],
            ['name' => 'Kenya', 'continent' => 'Africa', 'code' => '+254'],
            ['name' => 'Lesotho', 'continent' => 'Africa', 'code' => '+266'],
            ['name' => 'Liberia', 'continent' => 'Africa', 'code' => '+231'],
            ['name' => 'Libya', 'continent' => 'Africa', 'code' => '+218'],
            ['name' => 'Madagascar', 'continent' => 'Africa', 'code' => '+261'],
            ['name' => 'Malawi', 'continent' => 'Africa', 'code' => '+265'],
            ['name' => 'Mali', 'continent' => 'Africa', 'code' => '+223'],
            ['name' => 'Mauritania', 'continent' => 'Africa', 'code' => '+222'],
            ['name' => 'Mauritius', 'continent' => 'Africa', 'code' => '+230'],
            ['name' => 'Morocco', 'continent' => 'Africa', 'code' => '+212'],
            ['name' => 'Mozambique', 'continent' => 'Africa', 'code' => '+258'],
            ['name' => 'Namibia', 'continent' => 'Africa', 'code' => '+264'],
            ['name' => 'Niger', 'continent' => 'Africa', 'code' => '+227'],
            ['name' => 'Nigeria', 'continent' => 'Africa', 'code' => '+234'],
            ['name' => 'Rwanda', 'continent' => 'Africa', 'code' => '+250'],
            ['name' => 'Sao Tome and Principe', 'continent' => 'Africa', 'code' => '+239'],
            ['name' => 'Senegal', 'continent' => 'Africa', 'code' => '+221'],
            ['name' => 'Seychelles', 'continent' => 'Africa', 'code' => '+248'],
            ['name' => 'Sierra Leone', 'continent' => 'Africa', 'code' => '+232'],
            ['name' => 'Somalia', 'continent' => 'Africa', 'code' => '+252'],
            ['name' => 'South Africa', 'continent' => 'Africa', 'code' => '+27'],
            ['name' => 'South Sudan', 'continent' => 'Africa', 'code' => '+211'],
            ['name' => 'Sudan', 'continent' => 'Africa', 'code' => '+249'],
            ['name' => 'Tanzania', 'continent' => 'Africa', 'code' => '+255'],
            ['name' => 'Togo', 'continent' => 'Africa', 'code' => '+228'],
            ['name' => 'Tunisia', 'continent' => 'Africa', 'code' => '+216'],
            ['name' => 'Uganda', 'continent' => 'Africa', 'code' => '+256'],
            ['name' => 'Zambia', 'continent' => 'Africa', 'code' => '+260'],
            ['name' => 'Zimbabwe', 'continent' => 'Africa', 'code' => '+263'],
            // Asia
            ['name' => 'Afghanistan', 'continent' => 'Asia', 'code' => '+93'],
            ['name' => 'Armenia', 'continent' => 'Asia', 'code' => '+374'],
            ['name' => 'Azerbaijan', 'continent' => 'Asia', 'code' => '+994'],
            ['name' => 'Bahrain', 'continent' => 'Asia', 'code' => '+973'],
            ['name' => 'Bangladesh', 'continent' => 'Asia', 'code' => '+880'],
            ['name' => 'Bhutan', 'continent' => 'Asia', 'code' => '+975'],
            ['name' => 'Brunei', 'continent' => 'Asia', 'code' => '+673'],
            ['name' => 'Cambodia', 'continent' => 'Asia', 'code' => '+855'],
            ['name' => 'China', 'continent' => 'Asia', 'code' => '+86'],
            ['name' => 'Cyprus', 'continent' => 'Asia', 'code' => '+357'],
            ['name' => 'Georgia', 'continent' => 'Asia', 'code' => '+995'],
            ['name' => 'India', 'continent' => 'Asia', 'code' => '+91'],
            ['name' => 'Indonesia', 'continent' => 'Asia', 'code' => '+62'],
            ['name' => 'Iran', 'continent' => 'Asia', 'code' => '+98'],
            ['name' => 'Iraq', 'continent' => 'Asia', 'code' => '+964'],
            ['name' => 'Israel', 'continent' => 'Asia', 'code' => '+972'],
            ['name' => 'Japan', 'continent' => 'Asia', 'code' => '+81'],
            ['name' => 'Jordan', 'continent' => 'Asia', 'code' => '+962'],
            ['name' => 'Kazakhstan', 'continent' => 'Asia', 'code' => '+7'],
            ['name' => 'Kuwait', 'continent' => 'Asia', 'code' => '+965'],
            ['name' => 'Kyrgyzstan', 'continent' => 'Asia', 'code' => '+996'],
            ['name' => 'Laos', 'continent' => 'Asia', 'code' => '+856'],
            ['name' => 'Lebanon', 'continent' => 'Asia', 'code' => '+961'],
            ['name' => 'Malaysia', 'continent' => 'Asia', 'code' => '+60'],
            ['name' => 'Maldives', 'continent' => 'Asia', 'code' => '+960'],
            ['name' => 'Mongolia', 'continent' => 'Asia', 'code' => '+976'],
            ['name' => 'Myanmar', 'continent' => 'Asia', 'code' => '+95'],
            ['name' => 'Nepal', 'continent' => 'Asia', 'code' => '+977'],
            ['name' => 'North Korea', 'continent' => 'Asia', 'code' => '+850'],
            ['name' => 'Oman', 'continent' => 'Asia', 'code' => '+968'],
            ['name' => 'Pakistan', 'continent' => 'Asia', 'code' => '+92'],
            ['name' => 'Palestine', 'continent' => 'Asia', 'code' => '+970'],
            ['name' => 'Philippines', 'continent' => 'Asia', 'code' => '+63'],
            ['name' => 'Qatar', 'continent' => 'Asia', 'code' => '+974'],
            ['name' => 'Saudi Arabia', 'continent' => 'Asia', 'code' => '+966'],
            ['name' => 'Singapore', 'continent' => 'Asia', 'code' => '+65'],
            ['name' => 'South Korea', 'continent' => 'Asia', 'code' => '+82'],
            ['name' => 'Sri Lanka', 'continent' => 'Asia', 'code' => '+94'],
            ['name' => 'Syria', 'continent' => 'Asia', 'code' => '+963'],
            ['name' => 'Tajikistan', 'continent' => 'Asia', 'code' => '+992'],
            ['name' => 'Thailand', 'continent' => 'Asia', 'code' => '+66'],
            ['name' => 'Timor-Leste', 'continent' => 'Asia', 'code' => '+670'],
            ['name' => 'Turkey', 'continent' => 'Asia', 'code' => '+90'],
            ['name' => 'Turkmenistan', 'continent' => 'Asia', 'code' => '+993'],
            ['name' => 'United Arab Emirates', 'continent' => 'Asia', 'code' => '+971'],
            ['name' => 'Uzbekistan', 'continent' => 'Asia', 'code' => '+998'],
            ['name' => 'Vietnam', 'continent' => 'Asia', 'code' => '+84'],
            ['name' => 'Yemen', 'continent' => 'Asia', 'code' => '+967'],
            // Europe
            ['name' => 'Albania', 'continent' => 'Europe', 'code' => '+355'],
            ['name' => 'Andorra', 'continent' => 'Europe', 'code' => '+376'],
            ['name' => 'Austria', 'continent' => 'Europe', 'code' => '+43'],
            ['name' => 'Belarus', 'continent' => 'Europe', 'code' => '+375'],
            ['name' => 'Belgium', 'continent' => 'Europe', 'code' => '+32'],
            ['name' => 'Bosnia and Herzegovina', 'continent' => 'Europe', 'code' => '+387'],
            ['name' => 'Bulgaria', 'continent' => 'Europe', 'code' => '+359'],
            ['name' => 'Croatia', 'continent' => 'Europe', 'code' => '+385'],
            ['name' => 'Czech Republic', 'continent' => 'Europe', 'code' => '+420'],
            ['name' => 'Denmark', 'continent' => 'Europe', 'code' => '+45'],
            ['name' => 'Estonia', 'continent' => 'Europe', 'code' => '+372'],
            ['name' => 'Finland', 'continent' => 'Europe', 'code' => '+358'],
            ['name' => 'France', 'continent' => 'Europe', 'code' => '+33'],
            ['name' => 'Germany', 'continent' => 'Europe', 'code' => '+49'],
            ['name' => 'Greece', 'continent' => 'Europe', 'code' => '+30'],
            ['name' => 'Hungary', 'continent' => 'Europe', 'code' => '+36'],
            ['name' => 'Iceland', 'continent' => 'Europe', 'code' => '+354'],
            ['name' => 'Ireland', 'continent' => 'Europe', 'code' => '+353'],
            ['name' => 'Italy', 'continent' => 'Europe', 'code' => '+39'],
            ['name' => 'Kosovo', 'continent' => 'Europe', 'code' => '+383'],
            ['name' => 'Latvia', 'continent' => 'Europe', 'code' => '+371'],
            ['name' => 'Liechtenstein', 'continent' => 'Europe', 'code' => '+423'],
            ['name' => 'Lithuania', 'continent' => 'Europe', 'code' => '+370'],
            ['name' => 'Luxembourg', 'continent' => 'Europe', 'code' => '+352'],
            ['name' => 'Malta', 'continent' => 'Europe', 'code' => '+356'],
            ['name' => 'Moldova', 'continent' => 'Europe', 'code' => '+373'],
            ['name' => 'Monaco', 'continent' => 'Europe', 'code' => '+377'],
            ['name' => 'Montenegro', 'continent' => 'Europe', 'code' => '+382'],
            ['name' => 'Netherlands', 'continent' => 'Europe', 'code' => '+31'],
            ['name' => 'North Macedonia', 'continent' => 'Europe', 'code' => '+389'],
            ['name' => 'Norway', 'continent' => 'Europe', 'code' => '+47'],
            ['name' => 'Poland', 'continent' => 'Europe', 'code' => '+48'],
            ['name' => 'Portugal', 'continent' => 'Europe', 'code' => '+351'],
            ['name' => 'Romania', 'continent' => 'Europe', 'code' => '+40'],
            ['name' => 'Russia', 'continent' => 'Europe', 'code' => '+7'],
            ['name' => 'San Marino', 'continent' => 'Europe', 'code' => '+378'],
            ['name' => 'Serbia', 'continent' => 'Europe', 'code' => '+381'],
            ['name' => 'Slovakia', 'continent' => 'Europe', 'code' => '+421'],
            ['name' => 'Slovenia', 'continent' => 'Europe', 'code' => '+386'],
            ['name' => 'Spain', 'continent' => 'Europe', 'code' => '+34'],
            ['name' => 'Sweden', 'continent' => 'Europe', 'code' => '+46'],
            ['name' => 'Switzerland', 'continent' => 'Europe', 'code' => '+41'],
            ['name' => 'Ukraine', 'continent' => 'Europe', 'code' => '+380'],
            ['name' => 'United Kingdom', 'continent' => 'Europe', 'code' => '+44'],
            ['name' => 'Vatican City', 'continent' => 'Europe', 'code' => '+379'],
            // North America
            ['name' => 'Antigua and Barbuda', 'continent' => 'North America', 'code' => '+1'],
            ['name' => 'Bahamas', 'continent' => 'North America', 'code' => '+1'],
            ['name' => 'Barbados', 'continent' => 'North America', 'code' => '+1'],
            ['name' => 'Belize', 'continent' => 'North America', 'code' => '+501'],
            ['name' => 'Canada', 'continent' => 'North America', 'code' => '+1'],
            ['name' => 'Costa Rica', 'continent' => 'North America', 'code' => '+506'],
            ['name' => 'Cuba', 'continent' => 'North America', 'code' => '+53'],
            ['name' => 'Dominica', 'continent' => 'North America', 'code' => '+1'],
            ['name' => 'Dominican Republic', 'continent' => 'North America', 'code' => '+1'],
            ['name' => 'El Salvador', 'continent' => 'North America', 'code' => '+503'],
            ['name' => 'Grenada', 'continent' => 'North America', 'code' => '+1'],
            ['name' => 'Guatemala', 'continent' => 'North America', 'code' => '+502'],
            ['name' => 'Haiti', 'continent' => 'North America', 'code' => '+509'],
            ['name' => 'Honduras', 'continent' => 'North America', 'code' => '+504'],
            ['name' => 'Jamaica', 'continent' => 'North America', 'code' => '+1'],
            ['name' => 'Mexico', 'continent' => 'North America', 'code' => '+52'],
            ['name' => 'Nicaragua', 'continent' => 'North America', 'code' => '+505'],
            ['name' => 'Panama', 'continent' => 'North America', 'code' => '+507'],
            ['name' => 'Saint Kitts and Nevis', 'continent' => 'North America', 'code' => '+1'],
            ['name' => 'Saint Lucia', 'continent' => 'North America', 'code' => '+1'],
            ['name' => 'Saint Vincent and the Grenadines', 'continent' => 'North America', 'code' => '+1'],
            ['name' => 'Trinidad and Tobago', 'continent' => 'North America', 'code' => '+1'],
            ['name' => 'United States', 'continent' => 'North America', 'code' => '+1'],
            // Oceania
            ['name' => 'Australia', 'continent' => 'Oceania', 'code' => '+61'],
            ['name' => 'Fiji', 'continent' => 'Oceania', 'code' => '+679'],
            ['name' => 'Kiribati', 'continent' => 'Oceania', 'code' => '+686'],
            ['name' => 'Marshall Islands', 'continent' => 'Oceania', 'code' => '+692'],
            ['name' => 'Micronesia', 'continent' => 'Oceania', 'code' => '+691'],
            ['name' => 'Nauru', 'continent' => 'Oceania', 'code' => '+674'],
            ['name' => 'New Zealand', 'continent' => 'Oceania', 'code' => '+64'],
            ['name' => 'Palau', 'continent' => 'Oceania', 'code' => '+680'],
            ['name' => 'Papua New Guinea', 'continent' => 'Oceania', 'code' => '+675'],
            ['name' => 'Samoa', 'continent' => 'Oceania', 'code' => '+685'],
            ['name' => 'Solomon Islands', 'continent' => 'Oceania', 'code' => '+677'],
            ['name' => 'Tonga', 'continent' => 'Oceania', 'code' => '+676'],
            ['name' => 'Tuvalu', 'continent' => 'Oceania', 'code' => '+688'],
            ['name' => 'Vanuatu', 'continent' => 'Oceania', 'code' => '+678'],
            // South America
            ['name' => 'Argentina', 'continent' => 'South America', 'code' => '+54'],
            ['name' => 'Bolivia', 'continent' => 'South America', 'code' => '+591'],
            ['name' => 'Brazil', 'continent' => 'South America', 'code' => '+55'],
            ['name' => 'Chile', 'continent' => 'South America', 'code' => '+56'],
            ['name' => 'Colombia', 'continent' => 'South America', 'code' => '+57'],
            ['name' => 'Ecuador', 'continent' => 'South America', 'code' => '+593'],
            ['name' => 'Guyana', 'continent' => 'South America', 'code' => '+592'],
            ['name' => 'Paraguay', 'continent' => 'South America', 'code' => '+595'],
            ['name' => 'Peru', 'continent' => 'South America', 'code' => '+51'],
            ['name' => 'Suricountry', 'continent' => 'South America', 'code' => '+597'],
            ['name' => 'Uruguay', 'continent' => 'South America', 'code' => '+598'],
            ['name' => 'Venezuela', 'continent' => 'South America', 'code' => '+58'],
        ];
        
        
        Country::insert($countries);
    }
}
